language: python
python:
# @modified 20200808 - Task #3608: Update Skyline to Python 3.8.3 and deps
#  - "2.7"
  - "3.8"
install:
  - wget http://repo.continuum.io/archive/Anaconda-1.6.0-Linux-x86_64.sh
  - chmod +x Anaconda-1.6.0-Linux-x86_64.sh
  - ./Anaconda-1.6.0-Linux-x86_64.sh -b
  - PYTHONPATH= PATH=/home/travis/anaconda/bin:$PATH pip install -r requirements.txt --use-mirrors
  - PYTHONPATH= PATH=/home/travis/anaconda/bin:$PATH pip install patsy --use-mirrors
  - PYTHONPATH= PATH=/home/travis/anaconda/bin:$PATH pip install msgpack_python --use-mirrors
  - pip install pep8 --use-mirrors
script:
  - PYTHONPATH= PATH=/home/travis/anaconda/bin:$PATH nosetests -v --nocapture
  - pep8 --exclude=migrations --ignore=E501,E251,E265,E402 ./
notifications:
  email: false
